FROM stilliard/pure-ftpd:latest

#Se trouvent dans src/ les fichiers utiles a root pour gérer les users
COPY src/* /root/

#Remplacer localhost par le nom du serveur
ENV PUBLICHOST localhost

Expose 21 
Expose 30000-30009

